// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6;

namespace Mission6.Migrations
{
    [DbContext(typeof(NewTaskContext))]
    [Migration("20220210044006_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryResp");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryTitle = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryTitle = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryTitle = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryTitle = "Church"
                        });
                });

            modelBuilder.Entity("Mission6.Models.CoveyForm", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quadrant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TaskResp");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            Completed = true,
                            DueDate = "09-09-2022",
                            Quadrant = "Important & Urgent",
                            Task = "Win Win Win"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Completed = true,
                            DueDate = "09-10-2022",
                            Quadrant = "Important & Not Urgent",
                            Task = "Win Win Lose"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 3,
                            Completed = false,
                            DueDate = "09-11-2022",
                            Quadrant = "Not Important & Urgent",
                            Task = "Win Lose Lose"
                        },
                        new
                        {
                            TaskId = 4,
                            CategoryId = 4,
                            Completed = false,
                            DueDate = "09-12-2022",
                            Quadrant = "Not Important & Not Urgent",
                            Task = "Lose Lose Lose"
                        });
                });

            modelBuilder.Entity("Mission6.Models.CoveyForm", b =>
                {
                    b.HasOne("Mission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
